name: 'FTP Deploy (Parallel)'
author: 'Murillo HMS'
description: 'Deploy FTP de alta performance com conexões paralelas para Angular e outros apps.'
inputs:
  host:
    description: 'Endereço do servidor FTP'
    required: true
  user:
    description: 'Usuário do FTP'
    required: true
  password:
    description: 'Senha do FTP'
    required: true
  forceSsl:
    description: 'Forçar criptografia SSL (true/false)'
    required: false
    default: 'false'
  localDir:
    description: 'Pasta local do build (ex: dist/projeto/browser)'
    required: false
    default: '.'
  remoteDir:
    description: 'Pasta de destino no servidor'
    required: false
    default: 'public_html'
  options:
    description: 'Opções extras para o comando mirror do lftp'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'zap'